// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstScaffolding.Models;

public partial class DepartmentUI
{
    public int DepartmentId { get; set; }

    public int? DepartmentNumber { get; set; }

    public string DepartmentName { get; set; }

    public int? CompanyId { get; set; }

    public virtual CompanyUI Company { get; set; }
}