// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstScaffolding.Models;

public partial class EmailUI
{
    public int EmailId { get; set; }

    public int? EmployeeId { get; set; }

    public string Email1 { get; set; }

    public virtual EmployeeUI Employee { get; set; }
}