// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstScaffolding.Models;

public partial class EmployeeUI
{
    public int EmployeeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public virtual ICollection<AddressUI> Addresses { get; set; } = new List<AddressUI>();

    public virtual ICollection<EmailUI> Emails { get; set; } = new List<EmailUI>();

    public virtual ICollection<PhoneNumberUI> PhoneNumbers { get; set; } = new List<PhoneNumberUI>();
}