// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstScaffolding.Models;

public partial class City
{
    public int PostalCode { get; set; }

    public string City1 { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}