// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseFirstScaffolding.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}